name: Check Research Files

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*-root.tsx'

jobs:
  check-research-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*-root.tsx'
          
      - name: Check for research files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Initialize array for missing research files
          missing=()
          
          # Check each changed -root.tsx file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Get the directory containing the file
            dir=$(dirname "$file")
            
            # Check if research file exists in that directory
            if [ ! -f "$dir/research.mdx" ] && [ ! -f "$dir/research.md" ] && 
               [ ! -f "$dir/research.tsx" ] && [ ! -f "$dir/research.ts" ] && 
               [ ! -f "$dir/research.js" ]; then
              missing+=("$dir")
            fi
          done
          
          # Report missing research files
          if [ ${#missing[@]} -gt 0 ]; then
            echo "::error title=Missing Research Documentation::❌ Research documentation is required for component folders"
            echo "::group::Components missing required research files"
            for dir in "${missing[@]}"; do
              echo "::error::📁 $dir - Missing research file (research.mdx/md/tsx/ts/js)"
              echo "📝 Each directory containing a -root.tsx file must include a research file that documents:"
              echo "   - Component research and rationale"
              echo "   - Accessibility considerations"
              echo "   - Design decisions"
              echo "   - Usage guidelines"
            done
            echo "::endgroup::"
            
            echo "::group::How to fix"
            echo "Create a research.mdx file in each of the following directories:"
            for dir in "${missing[@]}"; do
              echo "✅ $dir/research.mdx"
            done
            echo "See https://qwik.design/contributing/research/ for more info on how to write research files."
            echo "::endgroup::"
            
            exit 1
          else
            echo "✅ All directories with -root.tsx files have research files."
          fi