name: CI

permissions:
  contents: read

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [22.12]
        experimental: [false]
    name: 👷 QDS CI Node-${{ matrix.node }} under ${{ matrix.os }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: 🎉 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: ✨ Install dependencies
        run: |
          npm install -g pnpm@8
          pnpm install

      - name: ✅ Check code style
        run: pnpm check